language: java

jdk:
  - oraclejdk8
before_install:
  # workaround for travis settings.xml
- cat ~/.m2/settings.xml
- touch settings.xml
- echo "<settings></settings>" > emptysettings.xml

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -s emptysettings.xml
script: mvn clean install -s emptysettings.xml
